config/routes.rb
Rails.application.routes.draw do
  resources :games
  resources :projects
  resources :sessions, only: [:create, :new, :destroy]

  post '/add_image' => 'projects#add_image'
  get '/delete_image' => 'projects#delete_image'
  
  post '/add_main_image' => 'projects#add_main_image'
  get '/delete_main_image' => 'projects#delete_main_image'

  root 'main#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
    belongs_to :project


    def store_to_public
        dir = Rails.root.join("public", "project_images/#{project_id}").to_s
        Dir.mkdir(dir) unless File.exists?(dir)
        File.open(Rails.root.join("public", "project_images/#{project_id}/#{title}").to_s, 'wb') do |file|
            file.write(Base64.decode64(base64))
        end
    end

    def path
        "/project_images/#{project_id}/#{title}"
    end

    def self.store_all
        Image.all.each do |image|
            image.store_to_public
        end
    end
    
end

app/models/project.rb
class Project < ApplicationRecord
     has_many :images

    def store_to_public
        dir = Rails.root.join("public", "project_images/#{id}").to_s
        Dir.mkdir dir unless File.exists?(dir)
        File.open(Rails.root.join("public", "project_images/#{id}/#{main_img}").to_s, 'wb') do |file|
            file.write(Base64.decode64(main_img_base64))
        end
    end

    def img_path
        "/project_images/#{id}/#{main_img}"
    end

    def self.store_all
        Project.all.each do |project|
            project.store_to_public
        end
    end
end

app/models/site_user.rb
class SiteUser
  include ActiveModel::Model

  attr_accessor :username, :password

  def login_valid?
    username == 'Adela' && password == '1234'
    # username == 'Adela' && password == 'My_157_Inception'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  ApplicationNotAuthenticated = Class.new(StandardError)

  rescue_from ApplicationNotAuthenticated do
    respond_to do |format|
      format.json { render json: { errors: [message: "401 Not Authorized"] }, status: 401 }
      format.html do
        flash[:notice] = "Not Authorized to access this page, plese log in"
        redirect_to new_session_path
      end
      format.any { head 401 }
    end
  end

  def authentication_required!
    session[:current_user] || raise(ApplicationNotAuthenticated)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
        @projects = Project.order(:order)
    end
end

app/controllers/projects_controller.rb
require 'base64'

class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authentication_required!
  layout 'admin-app'
  
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.order(:order)
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def delete_image
    pp params

    Image.delete(params['id'])

    redirect_to action: "show", id: params['project_id']
  end

  def delete_main_image
    pp params

    project = Project.find_by_id(params['project_id'])

    if (project) 
      project.main_img = nil
      project.main_img_cont_type = nil
      project.main_img_base64 = nil
      project.save
    end

    redirect_to action: "show", id: params['project_id']
  end

  def add_main_image
    file = params['file']
    project = Project.find_by_id(params['project_id'])

    if project && file
      project.main_img = file.original_filename
      project.main_img_cont_type = file.content_type
      project.main_img_base64 = Base64.encode64(file.read)
      project.save
      project.store_to_public
    else 
      flash[:notice] = "Please select file to upload."
    end

    redirect_to action: "show", id: params['project_id']
  end

  def add_image
    file = params['file']
    project = Project.find_by_id(params['project_id'])

    if project && file
      image = Image.create(title: file.original_filename, content_type: file.content_type, base64: Base64.encode64(file.read))
      project.images << image
      project.save
      image.store_to_public
      redirect_to action: "show", id: params['project_id'], :anchor => 'add_image_block'
    else 
      flash[:notice] = "Please select file to upload."
      redirect_to action: "show", id: params['project_id']
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :description, :author, :place, :realization, :investor, :order, :coworker, :custom1, :custom2, :custom3, :custom4)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @site_user = SiteUser.new
  end

  def create
    sleep 1 # you can add sleep here  if you want to  slow down brute force attack
              # for normal application this is bad idea but for one
              # user login no-one care

    site_user_params = params.require(:site_user)

    @site_user = SiteUser.new
      .tap { |su| su.username = site_user_params[:username] }
      .tap { |su| su.password = site_user_params[:password] }

    if @site_user.login_valid?
      session[:current_user] = true
      redirect_to '/projects'
    else
      @site_user.password = nil
      flash[:notice] = 'Wrong credentials'
      render 'new'
    end
  end

  def destroy
    reset_session
    redirect_to '/'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/admin-app.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stockwerk Admin Area</title>
    <%= csrf_meta_tags %>
    
    <link rel="shortcut icon" href="/img/favicon.ico" type="image/x-icon">
    <link href="/src/css/styles.css" rel="stylesheet">
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <header>
      <div class="wrap">
      <% if session[:current_user] %>
        <li class="log">
          <div class="item"><%= link_to 'LOGOUT', session_path('logout'), method: :delete %>
          </div>
        </li>
      <% end %>
      </div>
    </header>
    <div>
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StockWerk</title>
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <link href="/src/css/styles.css" rel="stylesheet">
    <link rel="shortcut icon" href="/src/img/favicon.ico" type="image/x-icon">
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
      <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<header>
	<div class="wrap">
		<div class="sidebar">
			<div class="logotype">
				<img src="/src/img/logo.png">
			</div>
			<nav>
				<div class="item"><a href="#projekty">PROJEKTY</a></div>
				<div class="item"><a href="#o nas">O NÁS</a></div>
				<div class="item"><a href="#spolupracujeme">SPOLUPRACUJEME</a></div>
				<div class="item"><a href="#kontakty">KONTAKTY</a></div>
			</nav>
		</div>
	</div>
</header>

<main class="">
	<div class="wrap">
		<div class="title" id="projekty">PROJEKTY</div>
		<div class="projects">
			<% @projects.each do |project| %>
				<div class="project">
					<!-- link that opens popup -->
					<a class="popup-with-form" href="#open-project-<%= project.id %>">
						<div class="discription">
							<div class="textWrap">
								<div class="text"><%= ActionController::Base.helpers.sanitize(project.title, :tags => ['br']) %></div>
							</div>
						</div>
						<img src="<%= project.img_path %>" alt="<%= project.title %>" />
					</a>	

					<!-- popup itself -->
					<section id="open-project-<%= project.id %>" class="white-popup-block mfp-hide" class="bg">
						<div class="wrapper">
							<div class="headline"><%= ActionController::Base.helpers.sanitize(project.title, :tags => []) %></div>
							<table>
								<tr>
									<td>Místo:</td><td><%= project.place %></td>
								</tr>
								<tr>
									<td>Stupeň:</td><td><%= project.realization %></td>
								</tr>
								<tr>
									<td>Investor:</td><td><%= project.investor %></td>
								</tr>
								<tr>
									<td>Team:</td><td><%= project.author %></td>
								</tr>
							</table>
							<p>
								<%= ActionController::Base.helpers.sanitize(project.description, :tags => ['br', 'p']) %>
							</p>
							<% project.images.each do |img| %>
							<div class="galerie">
								<div class="security"></div>
								<img class="img-in-popup" pre-src="<%= img.path %>" />
							</div>
							<% end %>
						</div>
					</section>
				</div>
			<% end %>
		</div>
	</div>
</main>
<section>
	<div class="wrap">
		<!-- o nas -->
		<div class="title" id="o nas">O NÁS</div>
		<img class="we" src="/src/img/team/team.jpg">
		<p>Autorský kolektiv StockWerk vznikl ze společné myšlenky přátel, které spojily podobné názory na architekturu. Chtěli jsme být dílnou „werkem“, 
			která pečuje o historické stavby a prostředí a to se nám podařilo. Věnujeme se různorodým projektům, ve kterých využíváme pestrý potenciál nejen členů našeho týmu, 
			ale i zkušených specialistů, se kterými dlouhodobě spolupracujeme. Soustředíme se na jednoduchost a čistý detail. Našimi klienty jsou soukromé osoby, obce, 
			státní instituce a neziskový sektor. Zajímáme se o dění kolem a podporujeme dobré nápady.
		</p>
		<div class="mainMembers">
			<div class="member">
				<img src="/src/img/team/Adela.jpg">
				<div class="name">Ing. arch. Adéla Poubová<br>ČKA 04 485</div>
				<div class="data">
					<div>Fakulta architektury</div>
					<div>ČVUT v Praze</div>
				</div>
				<div class="block">
					<span class="language">CZ</span>
					<span class="language">RUS</span>
					<span class="language">DEU</span>
				</div>					
			</div>
			<div class="member">
				<img src="/src/img/team/BaraC.jpg">
				<div class="name">Bc. Barbora Cahová</div>
				<div class="data">
					<div>Fakulta architektury</div>
					<div>ČVUT v Praze</div>
				</div>
				<div class="block">
					<span class="language">CZ</span>
					<span class="language">ENG</span>
				</div>					
			</div>
		</div> 
		<div class="mainMembers">
			<div class="member">
				<img src="/src/img/team/BaraS.jpg">
				<div class="name">Ing. Barbora Studená</div>
				<div class="data">
					<div>Fakulta stavební</div>
					<div>ČVUT v Praze</div>
				</div>
				<div class="block">
					<span class="language">CZ</span>
					<span class="language">ENG</span>
				</div>					
			</div>
			<div class="member">
				<img src="/src/img/team/Lucie.jpg">
				<div class="name">Ing. Lucie Jamáriková</div>
				<div class="data">
					<div style="opacity:0">Ne ma facultu</div>
					<div>Vysoká škola obchodní v Praze</div>
				</div>
				<div class="block">
					<span class="language">CZ</span>
					<span class="language">ENG</span>
				</div>						
			</div>
		</div> 
		<!--
		<div class="members">
			<div class="member">
			...upto 3
			</div>
			
		</div>
		-->
		<!-- spolupracujeme -->
		<div class="title" id="spolupracujeme">SPOLUPRACUJEME</div>
		<p class="indent">Baví nás dobré a užitečné projekty a proto je podporujeme.</p>
		<p class="indent">Připravili jsme bezplatně projektovou dokumentaci k obnově barokní křížové cesty od Matyáše Bernarda Brauna ve Valči. 
			Ve spolupráci s obcí se podařilo získat prostředky na realizaci a tak nezůstal jen projekt v šuplíku, ale akce byla 
			v roce 2016 zrealizována.</p>
		<p class="indent">Nejen projektově podporujeme dění kolem 
		<a href="http://www.skoky.eu/" style="text-decoration: underline;">poutního místa ve Skocích</a>.</p> 
		<p class="indent">Jsme rádi, že jsme měli tu čest podílet se na obnově kulturní krajiny, znovuzrození valečských sadů.</p>
		<p>Děkujeme všem, se kterými spolupracujeme, bez kterých by naše práce nikdy nebyla kompletní.</p>
		<!-- kontakty -->
		<div class="title" id="kontakty">KONTAKTY</div>
		<div class="contact-cont">
			<div class="contact">
				<p>Sídlo společnosti:</p>
				<p>StockWerk s. r. o.</p>
				<p>info@stockwerk.cz</p>
				<p>+420 725 712 360</p>
				<p>Vodičkova 677/10</p>
				<p class="indent">110 00 Praha - Nové Město</p>
			</div>

			<div class="contact">
				<p>Kancelář:</p>
				<p>StockWerk s. r. o.</p>
				<p>info@stockwerk.cz</p>
				<p>+420 725 712 360</p>
				<p>Karmelitská 18</p>
				<p class="indent">118 00 Praha - Malá Strana</p>
			</div>
		</div>
		<div class="locations">
			<!-- <figure>
				<div class="location">
					<img src="/src/img/Praha.jpg">
				</div>
			</figure>
			<figure>
				<div class="location">
					<img src="/src/img/Valec.jpg">
				</div>
				<div class="location">
					<div>Náměstí 33, 364 55 Valeč.</div>
				</div>
			</figure>-->
			<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d2559.993056045524!2d14.403879273294068!3d50.08641687552347!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x470b94e3ad707395%3A0x1c93b8f0eddd90bc!2sKarmelitsk%C3%A1%20379%2F18%2C%20118%2000%20Mal%C3%A1%20Strana%2C%20Czechia!5e0!3m2!1sen!2sse!4v1573933047214!5m2!1sen!2sse" width="960" height="600" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
			
			<!--sidlo  <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d538.2570191771921!2d14.421282402743852!3d50.0788665310398!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x470b94f2587865f1%3A0xb5db6974b1b77404!2zVm9kacSNa292YSA2NzcvMTAsIDExMCAwMCBOb3bDqSBNxJtzdG8!5e0!3m2!1sru!2scz!4v1540413527883" width="960" height="600" frameborder="0" style="border:0" allowfullscreen></iframe> -->
		</div>
	</div>
</section>
<footer>
	<div class="wrap">
		<div class="copyright">&copy; Copyright 2017 - 2019 © StockWerk s.r.o. Všechna práva vyhrazena.</div>
	</div>
</footer>

app/views/projects/_form.html.erb
<%= form_for(project) do |f| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table class="inputHolder">
    <tbody>
      <tr>
        <td><%= f.label :Název %></td>
        <td><%= f.text_field :title %></td>
      </tr>
      <tr>
        <td><%= f.label :Místo %></td>
        <td><%= f.text_field :place %></td>
      </tr>
      <tr>
        <td><%= f.label :Stupeň %></td>
        <td><%= f.text_field :realization %></td>
      </tr>
      <tr>
        <td><%= f.label :Investor %></td>
        <td><%= f.text_field :investor %></td>
      </tr>
      <tr>
        <td><%= f.label :Team %></td>
        <td><%= f.text_field :author %></td>
      </tr>
      <tr>
        <td><%= f.label :Pořadí %></td>
        <td><%= f.number_field :order %></td>
      </tr>
      <tr>
        <td><%= f.label :Popis %></td>
        <td><%= f.text_area :description %></td>
      </tr>
    </tbody>
  </table>
  <div class="btnWrap">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div class="wrap">
    <div class="title">EDITING PROJECT</div>
    <div class="btnBack">
        <span><%= link_to 'Show', @project %></span>
        <span><%= link_to 'Back', projects_path %></span>
    </div>

    <%= render 'form', project: @project %>

</div>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>
<td colspan="3"></td>

<div class="wrap">
  <div class="title">PROJEKTY</div>
  <% @projects.each do |project| %>
    <table class="borderBlock">
      <tbody>
        <tr>
          <td></td>
          <td class="btnBack">
            <span><%= link_to 'Show', project %></span>
            <span><%= link_to 'Edit', edit_project_path(project) %></span>
            <span><%= link_to 'Delete', project, method: :delete, data: { confirm: 'Are you sure, you whant to delete project?' } %></span>
          </td>
        </tr>
        <tr>
          <td>Název:</td>
          <td><%= project.title %></td>
        </tr>
        <tr>
          <td>Místo:</td>
          <td><%= project.place %></td>
        </tr>
        <tr>
          <td>Stupeň:</td>
          <td><%= project.realization %></td>
        </tr>
        <tr>
          <td>Investor:</td>
          <td><%= project.investor %></td>
        </tr>
        <tr>
          <td>Team:</td>
          <td><%= project.author %></td>
        </tr>
        <tr>
          <td>Pořadí:</td>
          <td><%= project.order %></td>
        </tr>
        <tr>
          <td>Popis:</td>
          <td><%= project.description %></td>
        </tr>
      </tbody>
    </table>
  <% end %>
</div>
<div class="wrap">
  <div class="btn">
    <%= link_to 'New Project', new_project_path %>
  </div>
</div>

app/views/projects/new.html.erb
<div class="wrap">
    <div class="title">NEW PROJEKT</div>
    <div class="btnBack"><%= link_to 'Back', projects_path %></div>
    <%= render 'form', project: @project %>
</div>

app/views/projects/show.html.erb
<div class="wrap">
  <p id="notice"><%= notice %></p>

  <div class="btnBack">
    <span><%= link_to 'Edit', edit_project_path(@project) %></span>
    <span><%= link_to 'Back', projects_path %></span>
  </div>
  <table>
    <tbody>
      <tr>
        <td>Název:</td>
        <td><%= @project.title %></td>
      </tr>
      <tr>
        <td>Místo:</td>
        <td><%= @project.place %></td>
      </tr>
      <tr>
        <td>Stupeň:</td>
        <td><%= @project.realization %></td>
      </tr>
      <tr>
        <td>Investor:</td>
        <td><%= @project.investor %></td>
      </tr>
      <tr>
        <td>Team:</td>
        <td><%= @project.author %></td>
      </tr>
      <tr>
        <td>Pořadí:</td>
        <td><%= @project.order %></td>
      </tr>
      <tr>
        <td>Popis:</td>
        <td><%= @project.description %></td>
      </tr>
      <tr>
        <td>Hlavní obrázek:</td>
        <td><% if  @project.main_img %>
          <div class="imgMainBlock">
            <img src="data:<%= @project.main_img_cont_type %>;base64, <%= @project.main_img_base64 %>" height="100px" />
            <div class="imgDiscr"><%= @project.main_img %></div>
            <div class="imgDel">
              <a href="<%= "/delete_main_image?project_id=" + @project.id.to_s %>"><img src="/src/img/delete.png"/></a>
              <% else %>
              <%= form_tag("/add_main_image", method: "post", multipart: true) do %>
              <%= hidden_field_tag(:project_id, @project.id) %>
            </div>
          </div>
        </td>
      </tr>
      <tr>
        <td></td>
        <td>
            <%= file_field_tag 'file' %>
            <span class="btnAdd"><%= submit_tag("Add image") %></span>
            <% end %>
          <% end %>
        </td>
      </tr>
      <tr>
        <td>
          <%= form_tag("/add_image", method: "post", multipart: true) do %>
            <%= hidden_field_tag(:project_id, @project.id) %>
            <%= label_tag(:q, "Obrázky:") %>
        </td>
        <td>
            <%= file_field_tag 'file' %>
            <a name="add_image_block"></a>
            <span name="" class="btnAdd"><%= submit_tag("Add image") %></span>
          <% end %>
        </td>
      </tr>
      <tr>
        <td></td>
        <td>
          <% @project.images.each do |img| %>
          <div class="imgBlock">
            <img src="data:<%= img.content_type %>;base64, <%= img.base64 %>" height="100px" />
            <div class="imgDiscr"><%= img.title %></div>
            <div class="imgDel">
              <a href="<%= "/delete_image?id=" + img.id.to_s + "&project_id=" + @project.id.to_s %>"><img src="/src/img/delete.png"/></a>
            </div>
          </div>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
</div>